export const LOGIN_EMAIL_CHANGE = 'LOGIN_EMAIL_CHANGE'
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE'
export const ON_CHANGE_EMAIL = 'ON_CHANGE_EMAIL'
export const EMAIL_ERROR = 'EMAIL_ERROR'
export const PASSWORD_ERROR = 'PASSWORD_ERROR'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const ERROR_MESSAGE_2 = 'ERROR_MESSAGE_2'

